//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.14 at 05:16:47 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:com:tradedoubler:pf:model:xml:common", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tradedoubler.pf.model.xml.common;
